//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biblioteca
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class librosmclEntities : DbContext
    {
        public librosmclEntities()
            : base("name=librosmclEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<libro> libro { get; set; }
        public virtual DbSet<librosfavoritos> librosfavoritos { get; set; }
        public virtual DbSet<prestamos> prestamos { get; set; }
        public virtual DbSet<tipousuario> tipousuario { get; set; }
        public virtual DbSet<usuario> usuario { get; set; }
    }
}
